EFIP-5: Security Improvements for eETH/weETH
etherfi-protocol/smart-contracts pull request #77
Opened 2024-06-28 05:56 UTC by seongyun-ko

2024-06-28 21:32 UTC, solipsis commented on proposals/EFIP-5.md
> +It introduces a whitelist mechanism on `spender` of `permit`. It will only allow the permit to be signed only for the whitelisted addresses to be the `spender` such as the well-known DEXes or lending
-> "It introduces a whitelist mechanism on `spender` of `permit`.  It will only allow whitelisted addresses to be the `spender` such as the well-known DEXes or lending protocols."

Slight change of wording because it doesn't impose restriction on who can sign a permit, only the spender

2024-06-28 21:35 UTC, solipsis commented on proposals/EFIP-5.md
> +It introduces a blacklist mechanism on `transfer`. It will prevent the transfer of tokens to the blacklisted addresses. This will help to prevent the funds from being sent to the malicious contracts
"It will prevent the transfer of tokens to and from blacklisted addresses"

Mechanism is on both sending and receiving side

2024-06-28 21:35 UTC, solipsis commented on proposals/EFIP-5.md
> +        require(!blacklisted[_sender] || !blacklisted[_recipient], "EETH: blacklisted address");
I don't think this condition is quite what you want. I think you want `&&`. As written you are fine as long as both sender and recipient are not both blacklisted

2024-06-28 21:37 UTC, solipsis requested changes
Couple small wording recommendations, and I believe an issue on your blacklist condition

2024-06-30 23:37 UTC, seongyun-ko commented on proposals/EFIP-5.md
> +        require(!blacklisted[_sender] || !blacklisted[_recipient], "EETH: blacklisted address");
yes, && thx!

2024-07-01 00:23 UTC, solipsis approved these changes

2024-07-01 01:15 UTC, seongyun-ko commented
Appreciate reviewing the PR @solipsis 
The implementation PR need to be made with reference to EFIP-5 :) Nice

2024-07-01 01:16 UTC, merged